name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: Describe the feature you are requesting. Remember to keep feature requests as atomic as possible (create a new issue for each separate feature).
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this feature needed?
    validations:
      required: true

  - type: dropdown
    id: estimated-importance
    validations:
      required: true
    attributes:
      label: Estimated usefulness for plugin users
      description: We appreciate your input on how useful this feature is for plugin users.
      options:
        - Useful for some users
        - Useful for many users
        - Useful for the majority of users
